//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagerWithNET_F.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDatPhong
    {
        public int MaChiTiet { get; set; }
        public Nullable<int> MaDatPhong { get; set; }
        public Nullable<int> MaPhong { get; set; }
        public string TenPhong { get; set; }
        public Nullable<int> DonGia { get; set; }
    }
}
