//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagerWithNET_F.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoSoVatChatPhong
    {
        public int MaCSVC { get; set; }
        public Nullable<int> MaPhong { get; set; }
        public Nullable<int> DieuHoa { get; set; }
        public Nullable<int> TiVi { get; set; }
        public Nullable<int> TuLanh { get; set; }
        public Nullable<int> PhongTam { get; set; }
        public Nullable<int> Giuong { get; set; }
        public Nullable<int> Ban { get; set; }
        public Nullable<int> Ghe { get; set; }
        public Nullable<int> DenNgu { get; set; }
        public Nullable<int> TuDo { get; set; }
    }
}
