//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagerWithNET_F.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatPhong
    {
        public int MaDatPhong { get; set; }
        public Nullable<int> MaKhachHang { get; set; }
        public Nullable<System.DateTime> NgayDatPhong { get; set; }
    }
}
